name: Bug Report
description: Template for reporting bugs or defects
projects: ['abitmedia-suite/3']
type: Bug
labels: ['bug']
body:
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Step-by-step sequence to reproduce the bug.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll to '...'
    validations:
      required: true

  - type: textarea
    id: expected-result
    attributes:
      label: Expected Result
      description: What should happen when following the steps.
      placeholder: "Description of expected behavior"
    validations:
      required: true

  - type: textarea
    id: actual-result
    attributes:
      label: Actual Result
      description: What actually happens when following the steps.
      placeholder: "Description of actual behavior"
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Environment details where the bug occurs.
      placeholder: |
        - Operating system:
        - Browser and version:
        - App version:
        - Device:
    validations:
      required: false

  - type: textarea
    id: evidence
    attributes:
      label: Evidence
      description: Screenshots, logs, or relevant error messages.
      placeholder: "Drag images or paste logs here"
    validations:
      required: false

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: Technical impact of the bug.
      options:
        - Trivial
        - Minor
        - Major
        - Critical
    validations:
      required: true

  - type: dropdown
    id: reproducibility
    attributes:
      label: Reproducibility
      description: How often the bug occurs.
      options:
        - Always
        - Sometimes
        - Only once
    validations:
      required: true
