name: Historia de usuario
description: Plantilla para crear historias de usuario
type: Feature
labels: ['enhancement']
body:
  - type: input
    id: como
    attributes:
      label: Como
      placeholder: "Rol o tipo de usuario"
    validations:
      required: true

  - type: input
    id: quiero
    attributes:
      label: Quiero
      placeholder: "Acción o funcionalidad deseada"
    validations:
      required: true

  - type: input
    id: para
    attributes:
      label: Para
      placeholder: "Beneficio o valor esperado"
    validations:
      required: true

  - type: textarea
    id: criterios-aceptacion
    attributes:
      label: Criterios de aceptación
      description: Lista de criterios que deben cumplirse para que la historia esté completa.
      placeholder: |
        - Condición que debe cumplirse
        - Otra condición que debe cumplirse
    validations:
      required: false
